name: Hello World CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  First-activity-message-printing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Message Printing
        run: echo "Hello from GitHub Actions! Second Activity"

      - name: Codecov reporter
        uses: AlexRogalskiy/github-action-coverage-reporter@v2.0.1
        with:
          coverage_file: coverage/lcov.info
          report_title: 'Code Coverage Report'
