name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Don't use cache to avoid lock file errors

    - name: Install dependencies
      run: npm install

    - name: Build (if applicable)
      run: npm run build --if-present

    - name: Run tests
      run: npm test

  print-message:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Print a message
      run: echo "✅ Build complete! Hello from the print-message job!"
