name: Hello World CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  First-activity-message-printing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Message Printing
        run: echo "Hello from GitHub Actions!  First Activity"
