name: Hello World CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  First-activity-message-printing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Message Printing
        run: echo "Hello from GitHub Actions! Second Activity"

      - name: Generate dummy JSON coverage report
        run: |
          mkdir -p coverage/json
          echo '{' > coverage/json/coverage-final.json
          echo '  "dummy.js": {' >> coverage/json/coverage-final.json
          echo '    "lines": { "1": 1, "2": 1 }' >> coverage/json/coverage-final.json
          echo '  }' >> coverage/json/coverage-final.json
          echo '}' >> coverage/json/coverage-final.json

      - name: Codecov reporter
        uses: AlexRogalskiy/github-action-coverage-reporter@v2.0.1
        with:
          reportType: json
          args: coverage/json/coverage-final.json
