name: Hello World CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  First-activity-message-printing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Message Printing
        run: echo "Hello from GitHub Actions! Second Activity"

      - name: Generate proper dummy JSON coverage report
        run: |
          mkdir -p coverage/json
          cat <<EOF > coverage/json/coverage-final.json
          {
            "total": {
              "lines": {
                "total": 2,
                "covered": 2,
                "skipped": 0,
                "pct": 100
              },
              "statements": {
                "total": 2,
                "covered": 2,
                "skipped": 0,
                "pct": 100
              },
              "functions": {
                "total": 1,
                "covered": 1,
                "skipped": 0,
                "pct": 100
              },
              "branches": {
                "total": 0,
                "covered": 0,
                "skipped": 0,
                "pct": 100
              }
            }
          }
          EOF

      - name: Codecov reporter
        uses: AlexRogalskiy/github-action-coverage-reporter@v2.0.1
        with:
          reportType: json
          args: coverage/json/coverage-final.json
